### ISSUE TITLE
Heading levels shouldn't be skipped

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/VBA-Docs#800] opened 2019-02-22 16:41 UTC
Moving discussion from #799
This gets flagged by the rule https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md001 which is part of the MSDocs Authoring pack
It also isn't semantic HTML and causes issues for screen reader users.

**Comment by Linda-Editor** [comment] 2019-02-22 16:45
Right -- for many of these, this is only heading on the page, so if it causes issues, I can change it to bold formatting. But I don't want only one heading 2 on a page. Thanks for bringing this to my attention, but it is by design. Nevertheless, I'll take a look.

**Comment by nschonni** [comment] 2019-02-22 17:21
Curious about only using a single H2.
Is it because of the right-hand table of contents generation?

**Comment by Linda-Editor** [comment] 2019-02-22 17:46
@nschonni Yes. If the topic is about one thing, and the heading repeats the topic title, it doesn't make sense to have it in the TOC on the right side of the page. I changed all of these to bold headings. For the others in https://github.com/MicrosoftDocs/VBA-Docs/pull/799, I updated them manually after viewing their position on the page in its entirety. These are not items that should be changed without seeing the entire topic layout. I'm closing this issue.

**Closed by Linda-Editor** 2019-02-22 17:46 UTC
Labels: bug: documentation

**Comment by nschonni** [comment] 2019-02-22 18:03
Thanks!
There might be another rule that get's triggered depending on how you changed them :wink: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md036

**Comment by Linda-Editor** [comment] 2019-02-22 18:11
In the end, I think an editor should have more say over rules. :-)

**Comment by nschonni** [comment] 2019-02-22 18:27
For sure. I was going to send over a PR to add the `.markdownlint.json` with the rules that are currently failing disabled. I was just trying to clean up a few of the ones I thought were noncontroversial first :smile: 
I'm not sure if the MS content writers group will push for particular baseline ruleset later. Right now it's just semi-endorsed by being part of the Authoring pack. I haven't seen them ship a recommended ruleset though

**Comment by Linda-Editor** [comment] 2019-02-22 19:18
@nschonni I think at this point you shouldn't concern yourself with this for the vba-docs repo. Where I can use your help is spelling errors/spacing issues/code languages that are easy to miss. For all other issues, including formatting, just log an ISSUE with a link to the rule, and then I'll decide if we need to deal with it. Thanks.
